development:
  adapter: mysql
  database: agile_meetings_new_dev
  username: root
  password:

test:
  adapter: mysql
  database: agile_meetings_new_test
  username: root
  password: 

production:
  adapter: mysql
  database: agile_meetings_new_prod
  username: root
  password:

