require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MeetingTypesController do

  # This should return the minimal set of attributes required to create a valid
  # MeetingType. As you add validations to MeetingType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all meeting_types as @meeting_types" do
      meeting_type = MeetingType.create! valid_attributes
      get :index
      assigns(:meeting_types).should eq([meeting_type])
    end
  end

  describe "GET show" do
    it "assigns the requested meeting_type as @meeting_type" do
      meeting_type = MeetingType.create! valid_attributes
      get :show, :id => meeting_type.id
      assigns(:meeting_type).should eq(meeting_type)
    end
  end

  describe "GET new" do
    it "assigns a new meeting_type as @meeting_type" do
      get :new
      assigns(:meeting_type).should be_a_new(MeetingType)
    end
  end

  describe "GET edit" do
    it "assigns the requested meeting_type as @meeting_type" do
      meeting_type = MeetingType.create! valid_attributes
      get :edit, :id => meeting_type.id
      assigns(:meeting_type).should eq(meeting_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MeetingType" do
        expect {
          post :create, :meeting_type => valid_attributes
        }.to change(MeetingType, :count).by(1)
      end

      it "assigns a newly created meeting_type as @meeting_type" do
        post :create, :meeting_type => valid_attributes
        assigns(:meeting_type).should be_a(MeetingType)
        assigns(:meeting_type).should be_persisted
      end

      it "redirects to the created meeting_type" do
        post :create, :meeting_type => valid_attributes
        response.should redirect_to(MeetingType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved meeting_type as @meeting_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        MeetingType.any_instance.stub(:save).and_return(false)
        post :create, :meeting_type => {}
        assigns(:meeting_type).should be_a_new(MeetingType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MeetingType.any_instance.stub(:save).and_return(false)
        post :create, :meeting_type => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested meeting_type" do
        meeting_type = MeetingType.create! valid_attributes
        # Assuming there are no other meeting_types in the database, this
        # specifies that the MeetingType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MeetingType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => meeting_type.id, :meeting_type => {'these' => 'params'}
      end

      it "assigns the requested meeting_type as @meeting_type" do
        meeting_type = MeetingType.create! valid_attributes
        put :update, :id => meeting_type.id, :meeting_type => valid_attributes
        assigns(:meeting_type).should eq(meeting_type)
      end

      it "redirects to the meeting_type" do
        meeting_type = MeetingType.create! valid_attributes
        put :update, :id => meeting_type.id, :meeting_type => valid_attributes
        response.should redirect_to(meeting_type)
      end
    end

    describe "with invalid params" do
      it "assigns the meeting_type as @meeting_type" do
        meeting_type = MeetingType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MeetingType.any_instance.stub(:save).and_return(false)
        put :update, :id => meeting_type.id, :meeting_type => {}
        assigns(:meeting_type).should eq(meeting_type)
      end

      it "re-renders the 'edit' template" do
        meeting_type = MeetingType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MeetingType.any_instance.stub(:save).and_return(false)
        put :update, :id => meeting_type.id, :meeting_type => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested meeting_type" do
      meeting_type = MeetingType.create! valid_attributes
      expect {
        delete :destroy, :id => meeting_type.id
      }.to change(MeetingType, :count).by(-1)
    end

    it "redirects to the meeting_types list" do
      meeting_type = MeetingType.create! valid_attributes
      delete :destroy, :id => meeting_type.id
      response.should redirect_to(meeting_types_url)
    end
  end

end
